"""Gemini TTS voice catalog. Lifted verbatim from voice-palette/backend/main.py."""

GEMINI_VOICES = [
    {"id": "Achernar",       "name": "Achernar",       "gender": "female", "persona": "The Livewire",     "description": "Bright and high-energy with a youthful tone. Fast-paced, enthusiastic delivery that grabs attention.",                        "tags": ["bright", "youthful", "high-energy"],     "color": "rose",    "provider": "gemini"},
    {"id": "Achird",         "name": "Achird",         "gender": "male",   "persona": "The Neighbor",     "description": "Friendly and approachable. The voice next door — warm without trying.",                                                       "tags": ["friendly", "approachable", "warm"],      "color": "amber",   "provider": "gemini"},
    {"id": "Algenib",        "name": "Algenib",        "gender": "male",   "persona": "The Veteran",      "description": "Gravelly and textured. Carries the weight of a thousand stories.",                                                            "tags": ["gravelly", "textured", "rugged"],        "color": "stone",   "provider": "gemini"},
    {"id": "Algieba",        "name": "Algieba",        "gender": "male",   "persona": "The Velvet",       "description": "Smooth and pleasant. Effortlessly easy on the ears with a warm, polished delivery.",                                          "tags": ["smooth", "pleasant", "warm"],            "color": "sky",     "provider": "gemini"},
    {"id": "Alnilam",        "name": "Alnilam",        "gender": "male",   "persona": "The Commander",    "description": "Firm and strong. Every word delivered with conviction.",                                                                       "tags": ["firm", "strong", "decisive"],            "color": "zinc",    "provider": "gemini"},
    {"id": "Aoede",          "name": "Aoede",          "gender": "female", "persona": "The Muse",         "description": "Warm and melodic with a clear, bright tone. Friendly and natural — one of the most versatile female voices.",                  "tags": ["warm", "melodic", "clear"],              "color": "violet",  "provider": "gemini"},
    {"id": "Autonoe",        "name": "Autonoe",        "gender": "female", "persona": "The Optimist",     "description": "Bright and optimistic with a lively, upbeat character. Light and youthful energy.",                                           "tags": ["bright", "optimistic", "lively"],        "color": "yellow",  "provider": "gemini"},
    {"id": "Callirrhoe",     "name": "Callirrhoe",     "gender": "female", "persona": "The Dreamer",      "description": "Easy-going and relaxed. A soft, unhurried delivery suited to calm, contemplative content.",                                    "tags": ["relaxed", "soft", "calm"],               "color": "indigo",  "provider": "gemini"},
    {"id": "Charon",         "name": "Charon",         "gender": "male",   "persona": "The Anchor",       "description": "Deep, authoritative, and informative. A steady, trustworthy presence built for news and narration.",                           "tags": ["deep", "authoritative", "steady"],       "color": "blue",    "provider": "gemini"},
    {"id": "Despina",        "name": "Despina",        "gender": "female", "persona": "The Confidante",   "description": "Breathy, soft, and intimate. Flowing delivery that feels close and personal.",                                                 "tags": ["breathy", "soft", "intimate"],           "color": "pink",    "provider": "gemini"},
    {"id": "Enceladus",      "name": "Enceladus",      "gender": "male",   "persona": "The Narrator",     "description": "Warm and steady with a mid-range tone. Reliable and clean — well-suited to corporate narration and e-learning.",               "tags": ["warm", "steady", "neutral"],             "color": "cyan",    "provider": "gemini"},
    {"id": "Erinome",        "name": "Erinome",        "gender": "female", "persona": "The Sentinel",     "description": "Firm and precise. A clear, no-nonsense delivery with strong enunciation.",                                                     "tags": ["firm", "precise", "clear"],              "color": "teal",    "provider": "gemini"},
    {"id": "Fenrir",         "name": "Fenrir",         "gender": "male",   "persona": "The Dynamo",       "description": "Excitable and dynamic with a warm, energetic character. Crisp delivery with high expressiveness.",                             "tags": ["excitable", "dynamic", "energetic"],     "color": "red",     "provider": "gemini"},
    {"id": "Gacrux",         "name": "Gacrux",         "gender": "female", "persona": "The Elder",        "description": "Mature and experienced. A deeper female voice that speaks with quiet, lived-in authority.",                                    "tags": ["mature", "deep", "authoritative"],       "color": "emerald", "provider": "gemini"},
    {"id": "Iapetus",        "name": "Iapetus",        "gender": "male",   "persona": "The Orator",       "description": "Clear and articulate with a professional mid-range tone. Every syllable perfectly placed.",                                    "tags": ["clear", "articulate", "professional"],   "color": "slate",   "provider": "gemini"},
    {"id": "Kore",           "name": "Kore",           "gender": "female", "persona": "The Anchor",       "description": "Firm, confident, and high-energy with a bright, clear tone. A strong female voice that commands attention.",                   "tags": ["firm", "confident", "bright"],           "color": "fuchsia", "provider": "gemini"},
    {"id": "Laomedeia",      "name": "Laomedeia",      "gender": "female", "persona": "The Dawn",         "description": "Upbeat and lively. Bright with an optimistic lift — like the first light of morning.",                                        "tags": ["upbeat", "bright", "hopeful"],           "color": "orange",  "provider": "gemini"},
    {"id": "Leda",           "name": "Leda",           "gender": "female", "persona": "The Trailblazer",  "description": "Youthful and energetic with a crisp, friendly tone. Forward-leaning delivery with a spark of adventure.",                      "tags": ["youthful", "energetic", "crisp"],        "color": "lime",    "provider": "gemini"},
    {"id": "Orus",           "name": "Orus",           "gender": "male",   "persona": "The Judge",        "description": "Firm and decisive with a lively mid-range. Cuts through noise with clarity and authority.",                                    "tags": ["firm", "decisive", "lively"],            "color": "neutral", "provider": "gemini"},
    {"id": "Puck",           "name": "Puck",           "gender": "male",   "persona": "The Trickster",    "description": "Upbeat, conversational, and highly expressive. Mischievous charm with quick wit and natural flow.",                            "tags": ["upbeat", "expressive", "playful"],       "color": "green",   "provider": "gemini"},
    {"id": "Pulcherrima",    "name": "Pulcherrima",    "gender": "male",   "persona": "The Performer",    "description": "Forward and expressive with theatrical energy. A male voice that leans into performance.",                                     "tags": ["expressive", "theatrical", "bold"],      "color": "purple",  "provider": "gemini"},
    {"id": "Rasalgethi",     "name": "Rasalgethi",     "gender": "male",   "persona": "The Professor",    "description": "Informative and professional. A clear, measured male voice built for tutorials, walkthroughs, and lectures.",                  "tags": ["informative", "professional", "measured"],"color": "blue",   "provider": "gemini"},
    {"id": "Sadachbia",      "name": "Sadachbia",      "gender": "male",   "persona": "The Firecracker",  "description": "Lively and animated with high energy and personality. Bursts with enthusiasm and infectious drive.",                            "tags": ["lively", "animated", "enthusiastic"],    "color": "orange",  "provider": "gemini"},
    {"id": "Sadaltager",     "name": "Sadaltager",     "gender": "male",   "persona": "The Expert",       "description": "Knowledgeable and authoritative. Measured delivery that conveys expertise and credibility.",                                   "tags": ["authoritative", "measured", "expert"],   "color": "teal",    "provider": "gemini"},
    {"id": "Schedar",        "name": "Schedar",        "gender": "male",   "persona": "The Balance",      "description": "Even and balanced. Consistently smooth — never too much, never too little. A reliable all-rounder.",                           "tags": ["balanced", "smooth", "neutral"],         "color": "zinc",    "provider": "gemini"},
    {"id": "Sulafat",        "name": "Sulafat",        "gender": "male",   "persona": "The Hearth",       "description": "Warm and welcoming with a comfortable, unhurried tone. Like a cozy fireside conversation.",                                   "tags": ["warm", "welcoming", "comforting"],       "color": "amber",   "provider": "gemini"},
    {"id": "Umbriel",        "name": "Umbriel",        "gender": "male",   "persona": "The Drift",        "description": "Easy-going and calm. A laid-back delivery that never rushes — relaxed authority.",                                            "tags": ["easy-going", "calm", "relaxed"],         "color": "sky",     "provider": "gemini"},
    {"id": "Vindemiatrix",   "name": "Vindemiatrix",   "gender": "female", "persona": "The Healer",       "description": "Gentle and kind with a soothing quality. A soft female voice with genuine warmth in every word.",                             "tags": ["gentle", "soothing", "warm"],            "color": "rose",    "provider": "gemini"},
    {"id": "Zephyr",         "name": "Zephyr",         "gender": "female", "persona": "The Sunbeam",      "description": "Bright and clear with a smooth, effortlessly conversational tone. Youthful energy without losing polish.",                     "tags": ["bright", "clear", "conversational"],     "color": "yellow",  "provider": "gemini"},
    {"id": "Zubenelgenubi",  "name": "Zubenelgenubi",  "gender": "male",   "persona": "The Wanderer",     "description": "Casual and conversational. Effortlessly cool with a laid-back, unhurried delivery.",                                           "tags": ["casual", "conversational", "relaxed"],   "color": "stone",   "provider": "gemini"},
]

GEMINI_VOICE_IDS = {v["id"] for v in GEMINI_VOICES}

# Model name aliases — voice-palette's mapping kept verbatim.
GEMINI_MODELS = {"gemini-2.5-flash-tts", "gemini-2.5-pro-tts", "gemini-3.1-flash-tts"}
GEMINI_MODEL_MAP = {
    "gemini-2.5-flash-tts": "gemini-2.5-flash-preview-tts",
    "gemini-2.5-pro-tts": "gemini-2.5-pro-preview-tts",
    "gemini-3.1-flash-tts": "gemini-3.1-flash-tts-preview",
}
